spring.datasource.url=jdbc:mysql://localhost:3306/bookinghub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=bookinghub_app
spring.datasource.password=bookhub@7

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
